config/routes.rb
Rails.application.routes.draw do
  get 'livroshpazkaban/index'
  get 'livroshpazkaban/busca'
  get 'livroshpazkaban/livros'
  root 'homepage#index'
  get 'homepage/search'
  get 'homepage/livros'
  #post 'homepage/search'
  resources :books
  resources :authors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :gender, :age)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :pages, :author_id)
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  require_relative '../service/buscalivros'

  def index
  end

  def search
    @nomeDoElemento = params[:busca]
    @numeroDaPagina = 0
    @numeroDeElementos = 40
    @response = Googles.new(@nomeDoElemento, @numeroDaPagina, @numeroDeElementos)
    puts @response
    @response2 = @response.inicio
    puts @response2
    @livroAzkaban = JSON.parse(@response2.body)
  end


    
end

app/controllers/livroshpazkaban_controller.rb
class LivroshpazkabanController < ApplicationController
  def index
  end

  def busca
  end

  def livros
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/livroshpazkaban_helper.rb
module LivroshpazkabanHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>" class="col" >
  <div class="card mb-4 rounded-3 shadow-sm">
    <div class="card-header py-3">
      <h2 class="my-0 fw-normal">
        <strong><%= author.name %></strong>
      </h2>
    </div>
    <div class="card-body">
    
      <h3 class="card-title pricing-card-title">Gender: <small class="text-muted fw-light"><%= author.gender %></small></h3>

      <h3 class="card-title pricing-card-title">Age: <small class="text-muted fw-light"><%= author.age %></small></h3>

      <h3 class="card-title pricing-card-title">Books: </h3>

      <ul class="list-unstyled mt-3 mb-4">
        <% author.books.each do |book| %>
          <li class="card-title"><%= link_to book.title, book, class:"w-100 btn btn-lg btn-outline-info" %></li>
        <% end %>      
      </ul>
    </div>
  </div>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.select(:gender, ['Male', 'Female'], { include_blank: 'Select' }) %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authors</h1>

<div id="authors">
<div class="container">
<div class="row row-cols-1 row-cols-md-3 mb-3">
  <% @authors.each do |author| %>
    <div>
      <%= render author %>
      <p>
        <%= link_to "Show this author", author %>
      </p>
    </div>
  <% end %>
</div>
</div>
</div>










<%= link_to "New author", new_author_path %><br><br><br>
<%= link_to "Books page", books_path %>
<p><%= link_to "Home page", root_path %></p>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <%= button_to "Destroy this author", @author, method: :delete %>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

  <p>
    <strong>Pages:</strong>
    <%= book.pages %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author.name %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :pages, style: "display: block" %>
    <%= form.number_field :pages %>
  </div>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.collection_select( :author_id, Author.all, :id, :name, prompt: true) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %><br><br><br>
<%= link_to "AUTHORs page", authors_path %>
<p><%= link_to "Home page", root_path %></p>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/homepage/index.html.erb
<div class="title">
<h1><strong>Biblioteca.</strong></h1>




<div class="divbusca">
<%= form_with url:homepage_search_path, local:true, method: :get do %>
<div>
    <%= text_field_tag "busca", nil, placeholder: 'Digite o título do livro', class: 'buscarLivro'  %>
    <%= submit_tag "enviarBusca", value: "Buscar", class: 'buscarLivroBtn'%>
</div>
<% end %>
</div>



<div class="divbuscafooter">
</div>
</div>

app/views/homepage/livros.html.erb
def search
    @page = 0
    @response = HTTParty.get('https://www.googleapis.com/books/v1/volumes?q='+ params[:busca] + '&maxResults=40')
    #JSON.parse response, symbolize_names: true
    #puts response.body, response.code, response.message, 

    @livroAzkaban = JSON.parse(@response.body)

    @deyvid = "kasteh"
    
    

end

app/views/homepage/search.html.erb
<div class="searchPage">
    <div class="searchPageNavBar">
    <p><%= link_to "Biblioteca.", root_path %></p>
    <nav>
    <ul>
    <li><%= link_to "Books", books_path %></li>
    <li><%= link_to "AUTHORs page", authors_path %></li>
    </ul>
    </nav>
    </div>

    <div class="searchPageBody">
        <% @livroAzkaban['items'].each do |volume| %>
            <% if volume['volumeInfo'].include?('imageLinks') %>
                <%@titulo = volume['volumeInfo']['title']%>
                
                <div>
                    <%= image_tag volume['volumeInfo']['imageLinks']['thumbnail'], class: "searchPageBodyImage" %>
                    <div class="volumeDetalhes">
                        <p><%= @titulo%></p>
                    </div>
                </div>
            <% end %> 
        <% end %>
    </div>
    <div class="searchPageFoot">
            <p>  <%= link_to "Books", books_path %></p>
            <p><%= link_to "AUTHORs page", authors_path %></p>
            <p><%= link_to "Home page", root_path %></p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <div class="containerBody">
    <%= yield %>
    </div>
  </body>
</html>

app/views/livroshpazkaban/busca.html.erb
<h1>Livroshpazkaban#busca</h1>
<p>Find me in app/views/livroshpazkaban/busca.html.erb</p>

app/views/livroshpazkaban/index.html.erb
<h1>Livroshpazkaban#index</h1>
<p>Find me in app/views/livroshpazkaban/index.html.erb</p>

app/views/livroshpazkaban/livros.html.erb
<h1>Livroshpazkaban#livros</h1>
<p>Find me in app/views/livroshpazkaban/livros.html.erb</p>